### ISSUE TITLE
Axis

### ISSUE THREAD

**Issue by ebanorafael** [depaulobrunna/stm32f4_projects#1]
Incoerencia de nome de parâmetro na função. _get_sensor() para o caso em que o sensor seja temperatura. Adicionar mais um número no typedef de eixo indicando nenhum eixo para acomodar o caso do sensor de temperatura. Sugestao MPU60x_NO_AXIS como numeração zero.

Trocar também if das funções get_sensor_axis por swtich case.

**Comment by depaulobrunna** [comment]
pronto
